In [1]:
frutas  = ['Maça', 'Banana', 'Abacaxi']
frutas

['Maça', 'Banana', 'Abacaxi']

In [4]:
frutas[0:3]

['Maça', 'Banana', 'Abacaxi']

In [5]:
frutas[:3]

['Maça', 'Banana', 'Abacaxi']

In [6]:
frutas[1:]

['Banana', 'Abacaxi']

In [7]:
frutas[-1]

'Abacaxi'

Loc
> Com o loc conseguimos pegar os registros que necessita dentro do dataframe. O pandas nos fornece esse comando para pegar uma determinada coluna pelo nome.

> loc[:,] - O loc espera dois parâmetros. O primeiro são as linhas e o segundo a coluna.





In [16]:
import pandas as pd
df_prouni = pd.read_excel('cursos-prouni.csv.xlsx')
df_prouni

grau              turno  mensalidade  bolsa_integral_cotas  \
0       Bacharelado           Integral      9999.99                  15.0   
1       Bacharelado            Noturno      9836.40                   1.0   
2       Bacharelado           Integral      9715.61                   2.0   
3       Bacharelado            Noturno      9689.34                   3.0   
4       Bacharelado           Integral      9674.34                   4.0   
...             ...                ...          ...                   ...   
41442  Licenciatura  Curso a Distância       149.00                   1.0   
41443   Tecnológico  Curso a Distância       144.00                   1.0   
41444   Tecnológico         Vespertino       139.00                   1.0   
41445   Bacharelado  Curso a Distância       139.00                   1.0   
41446   Tecnológico  Curso a Distância       139.00                   3.0   

       bolsa_integral_ampla  bolsa_parcial_cotas  bolsa_parcial_ampla  \
0                      14.0                  NaN                  NaN   
1                       NaN                  NaN                  NaN   
2                       5.0                  6.0                 10.0   
3                       2.0                  NaN                  NaN   
4                       1.0                  5.0                  2.0   
...                     ...                  ...                  ...   
41442                   NaN                  NaN                  NaN   
41443                   2.0                  2.0                  5.0   
41444                   NaN                  NaN                  NaN   
41445                   NaN                  NaN                  NaN   
41446                   1.0                  NaN                  NaN   

              curso_id                 curso_busca          cidade_busca  \
0         706710394154                    Medicina          Campo Grande   
1      104191210567043                  Enfermagem               Crateus   
2        1002328574024                    Medicina             Sao Paulo   
3      104191212798093                  Psicologia               Crateus   
4       65899611932754                    Medicina            Rio Branco   
...                ...                         ...                   ...   
41442     994312865605                  Sociologia  Paraiso do Tocantins   
41443   65868712869275                   Marketing           Sao VIcente   
41444    1056445674232  Gestão de Recursos Humanos              Brasilia   
41445      96781210935              Serviço Social               Vitoria   
41446  200467412868575            Gestão Ambiental              Santarem   

      uf_busca     cidade_filtro  \
0           MS  NTAwMjAwNDAyNzA0   
1           CE  MjMwNDAxODA0MTAz   
2           SP  MzUxNTA2MTUwMzA4   
3           CE  MjMwNDAxODA0MTAz   
4           AC  MTIwMjAwNDAwNDAx   
...        ...               ...   
41442       TO  MTcwMTAwNDE2MTA5   
41443       SP  MzUxNTA2MzUxMDA5   
41444       DF  NTMwMTAwMTAwMTA4   
41445       ES  MzIwMzAwOTA1MzA5   
41446       PA  MTUwMTAwMjA2ODA3   

                                       universidade_nome  \
0                      Universidade Anhanguera - UNIDERP   
1                      Faculdade Princesa do Oeste - FPO   
2              Universidade Cidade de São Paulo - UNICID   
3                      Faculdade Princesa do Oeste - FPO   
4                    Faculdade Barão do Rio Branco - FAB   
...                                                  ...   
41442                       Universidade Paulista - UNIP   
41443                     Faculdade de São VIcente - FSV   
41444  Centro Universitário Planalto do Distrito Fede...   
41445                       Universidade Paulista - UNIP   
41446                       Universidade Paulista - UNIP   

                                             campus_nome  campus_external_id  \
0                     CAMPO GRANDE - SEDE - Miguel Couto          

In [18]:
df_medicina = df_prouni[df_prouni['uf_busca'] == 'SP'	]
df_medicina

grau              turno  mensalidade  bolsa_integral_cotas  \
2       Bacharelado           Integral      9715.61                   2.0   
5       Bacharelado           Integral      9650.00                   8.0   
6       Bacharelado           Integral      9564.00                   3.0   
12      Bacharelado           Integral      8600.00                   2.0   
22      Bacharelado           Integral      8200.00                   2.0   
...             ...                ...          ...                   ...   
41438  Licenciatura  Curso a Distância       149.00                   0.0   
41439   Tecnológico  Curso a Distância       149.00                   0.0   
41440   Tecnológico  Curso a Distância       149.00                   0.0   
41441   Tecnológico  Curso a Distância       149.00                   0.0   
41443   Tecnológico  Curso a Distância       144.00                   1.0   

       bolsa_integral_ampla  bolsa_parcial_cotas  bolsa_parcial_ampla  \
2                       5.0                  6.0                 10.0   
5                      15.0                  NaN                  NaN   
6                       5.0                  NaN                  NaN   
12                      9.0                  NaN                  NaN   
22                      3.0                  4.0                  7.0   
...                     ...                  ...                  ...   
41438                   1.0                  NaN                  NaN   
41439                   1.0                  NaN                  NaN   
41440                   1.0                  NaN                  NaN   
41441                   1.0                  NaN                  NaN   
41443                   2.0                  2.0                  5.0   

              curso_id       curso_busca         cidade_busca uf_busca  \
2        1002328574024          Medicina            Sao Paulo       SP   
5          65781564964          Medicina  Presidente Prudente       SP   
6          65788486984          Medicina              Marilia       SP   
12      65881713994834          Medicina            Rio Claro       SP   
22     105596711902804          Medicina            Sao Paulo       SP   
...                ...               ...                  ...      ...   
41438     965912865605        Sociologia      Taboao da Serra       SP   
41439     965913826055  Gestão Comercial      Taboao da Serra       SP   
41440     966013826055  Gestão Comercial                Tatui       SP   
41441     967113826055  Gestão Comercial              Taubate       SP   
41443   65868712869275         Marketing          Sao VIcente       SP   

          cidade_filtro                                  universidade_nome  \
2      MzUxNTA2MTUwMzA4          Universidade Cidade de São Paulo - UNICID   
5      MzUwODAzNjQxNDA2           Universidade do Oeste Paulista - UNOESTE   
6      MzUwOTAzODI5MDA1                   Universidade de Marília - UNIMAR   
12     MzUwNjAyNjQzOTA3  Claretiano - Faculdade - Claretianorc - CLARET...   
22     MzUxNTA2MTUwMzA4                       Faculdade das Américas - FAM   
...                 ...                                                ...   
41438  MzUxNTA2MDUyODA5                       Universidade Paulista - UNIP   
41439  MzUxNTA2MDUyODA5                       Universidade Paulista - UNIP   
41440  MzUxMTA0MzU0MDAz                       Universidade Paulista - UNIP   
41441  MzUxMzA1MDU0MTAy                       Universidade Paulista - UNIP   
41443  MzUxNTA2MzUxMDA5                     Faculdade de São VIcente - FSV   

                                             campus_nome  campus_external_id  \
2      UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...             1002328   
5      CAMPUS I  SEDE ADMINISTRATIVA PRESIDENTE PRUDE...              657815   
6                    UNIDADE SEDE - Campus Universitario              657884   
12                CLARETIANO - FACULDADE - Cidade Claret           

Traga todas as linhas da coluna mensalidade:

In [22]:
df1 = df_medicina.loc[:, 'mensalidade']
df1

2        9715.61
5        9650.00
6        9564.00
12       8600.00
22       8200.00
          ...   
41438     149.00
41439     149.00
41440     149.00
41441     149.00
41443     144.00
Name: mensalidade, Length: 11533, dtype: float64

Traga desde a linha 41438 até a linha 41443, e traga a coluna 'mensalidade':

In [29]:
df2 = df_medicina.loc[41438:41443, ['curso_busca', 'mensalidade', 'turno']]
df2

curso_busca  mensalidade              turno
41438        Sociologia        149.0  Curso a Distância
41439  Gestão Comercial        149.0  Curso a Distância
41440  Gestão Comercial        149.0  Curso a Distância
41441  Gestão Comercial        149.0  Curso a Distância
41443         Marketing        144.0  Curso a Distância

iloc:
> A diferença entre o loc e o iloc: O loc são as locations, você consegue trazer as informações pelo nome da coluna (quando ela está nomeada), por exemplo, mas quando você tem um dataset que não está nomeado, e as colunas possuem um nome default, usa-se o iloc (pelo índice da coluna).

> Ambos são bem parecidos:
  * O primeiro parâmetro são as linhas que se quer retornar
  * E no segundo parâmetro as colunas.

A diferença é que ao invés de colocar o nome da coluna, coloca-se o índice.




Me traga todas as linhas, coluna 1:

In [30]:
df1 = df_medicina.iloc[:, 1]
df1

2                 Integral
5                 Integral
6                 Integral
12                Integral
22                Integral
               ...        
41438    Curso a Distância
41439    Curso a Distância
41440    Curso a Distância
41441    Curso a Distância
41443    Curso a Distância
Name: turno, Length: 11533, dtype: object

Retorne a primeira linha do dataframe:

In [33]:
df2 = df_medicina.iloc[0]
df2

grau                                                          Bacharelado
turno                                                            Integral
mensalidade                                                       9715.61
bolsa_integral_cotas                                                  2.0
bolsa_integral_ampla                                                  5.0
bolsa_parcial_cotas                                                   6.0
bolsa_parcial_ampla                                                  10.0
curso_id                                                    1002328574024
curso_busca                                                      Medicina
cidade_busca                                                    Sao Paulo
uf_busca                                                               SP
cidade_filtro                                            MzUxNTA2MTUwMzA4
universidade_nome               Universidade Cidade de São Paulo - UNICID
campus_nome             UNIVERSIDADE C

Retorne a informação do df_medicina da linha 0 a linha 1, de todas as colunas:

In [35]:
df3 = df_medicina.iloc[0:4, :]
df3

grau     turno  mensalidade  bolsa_integral_cotas  \
2   Bacharelado  Integral      9715.61                   2.0   
5   Bacharelado  Integral      9650.00                   8.0   
6   Bacharelado  Integral      9564.00                   3.0   
12  Bacharelado  Integral      8600.00                   2.0   

    bolsa_integral_ampla  bolsa_parcial_cotas  bolsa_parcial_ampla  \
2                    5.0                  6.0                 10.0   
5                   15.0                  NaN                  NaN   
6                    5.0                  NaN                  NaN   
12                   9.0                  NaN                  NaN   

          curso_id curso_busca         cidade_busca uf_busca  \
2    1002328574024    Medicina            Sao Paulo       SP   
5      65781564964    Medicina  Presidente Prudente       SP   
6      65788486984    Medicina              Marilia       SP   
12  65881713994834    Medicina            Rio Claro       SP   

       cidade_filtro                                  universidade_nome  \
2   MzUxNTA2MTUwMzA4          Universidade Cidade de São Paulo - UNICID   
5   MzUwODAzNjQxNDA2           Universidade do Oeste Paulista - UNOESTE   
6   MzUwOTAzODI5MDA1                   Universidade de Marília - UNIMAR   
12  MzUwNjAyNjQzOTA3  Claretiano - Faculdade - Claretianorc - CLARET...   

                                          campus_nome  campus_external_id  \
2   UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...             1002328   
5   CAMPUS I  SEDE ADMINISTRATIVA PRESIDENTE PRUDE...              657815   
6                 UNIDADE SEDE - Campus Universitario              657884   
12             CLARETIANO - FACULDADE - Cidade Claret              658817   

        nome  nota_integral_ampla  nota_integral_cotas  nota_parcial_ampla  \
2   Medicina               739.62               738.08              738.96   
5   Medicina               738.92               728.86                 NaN   
6   Medicina               744.16               735.00                 NaN   
12  Medicina               734.44               720.86                 NaN   

    nota_parcial_cotas  
2               718.64  
5                  NaN  
6                  NaN  
12                 NaN

Retorne todas as linhas, da coluna 2 até a 4:

In [36]:
df4 = df_medicina.iloc[:, 2:4]
df4

mensalidade  bolsa_integral_cotas
2          9715.61                   2.0
5          9650.00                   8.0
6          9564.00                   3.0
12         8600.00                   2.0
22         8200.00                   2.0
...            ...                   ...
41438       149.00                   0.0
41439       149.00                   0.0
41440       149.00                   0.0
41441       149.00                   0.0
41443       144.00                   1.0

[11533 rows x 2 columns]

Retorne a linha 1 a 5, das colunas 2 a 7:

In [41]:
df5 = df_medicina.iloc[1:5, 2:7]
df5

mensalidade  bolsa_integral_cotas  bolsa_integral_ampla  \
5        9650.0                   8.0                  15.0   
6        9564.0                   3.0                   5.0   
12       8600.0                   2.0                   9.0   
22       8200.0                   2.0                   3.0   

    bolsa_parcial_cotas  bolsa_parcial_ampla  
5                   NaN                  NaN  
6                   NaN                  NaN  
12                  NaN                  NaN  
22                  4.0                  7.0

Reset Índices:

> reset_index



In [42]:
df_medicina.reset_index()

index          grau              turno  mensalidade  \
0          2   Bacharelado           Integral      9715.61   
1          5   Bacharelado           Integral      9650.00   
2          6   Bacharelado           Integral      9564.00   
3         12   Bacharelado           Integral      8600.00   
4         22   Bacharelado           Integral      8200.00   
...      ...           ...                ...          ...   
11528  41438  Licenciatura  Curso a Distância       149.00   
11529  41439   Tecnológico  Curso a Distância       149.00   
11530  41440   Tecnológico  Curso a Distância       149.00   
11531  41441   Tecnológico  Curso a Distância       149.00   
11532  41443   Tecnológico  Curso a Distância       144.00   

       bolsa_integral_cotas  bolsa_integral_ampla  bolsa_parcial_cotas  \
0                       2.0                   5.0                  6.0   
1                       8.0                  15.0                  NaN   
2                       3.0                   5.0                  NaN   
3                       2.0                   9.0                  NaN   
4                       2.0                   3.0                  4.0   
...                     ...                   ...                  ...   
11528                   0.0                   1.0                  NaN   
11529                   0.0                   1.0                  NaN   
11530                   0.0                   1.0                  NaN   
11531                   0.0                   1.0                  NaN   
11532                   1.0                   2.0                  2.0   

       bolsa_parcial_ampla         curso_id       curso_busca  ... uf_busca  \
0                     10.0    1002328574024          Medicina  ...       SP   
1                      NaN      65781564964          Medicina  ...       SP   
2                      NaN      65788486984          Medicina  ...       SP   
3                      NaN   65881713994834          Medicina  ...       SP   
4                      7.0  105596711902804          Medicina  ...       SP   
...                    ...              ...               ...  ...      ...   
11528                  NaN     965912865605        Sociologia  ...       SP   
11529                  NaN     965913826055  Gestão Comercial  ...       SP   
11530                  NaN     966013826055  Gestão Comercial  ...       SP   
11531                  NaN     967113826055  Gestão Comercial  ...       SP   
11532                  5.0   65868712869275         Marketing  ...       SP   

          cidade_filtro                                  universidade_nome  \
0      MzUxNTA2MTUwMzA4          Universidade Cidade de São Paulo - UNICID   
1      MzUwODAzNjQxNDA2           Universidade do Oeste Paulista - UNOESTE   
2      MzUwOTAzODI5MDA1                   Universidade de Marília - UNIMAR   
3      MzUwNjAyNjQzOTA3  Claretiano - Faculdade - Claretianorc - CLARET...   
4      MzUxNTA2MTUwMzA4                       Faculdade das Américas - FAM   
...                 ...                                                ...   
11528  MzUxNTA2MDUyODA5                       Universidade Paulista - UNIP   
11529  MzUxNTA2MDUyODA5                       Universidade Paulista - UNIP   
11530  MzUxMTA0MzU0MDAz                       Universidade Paulista - UNIP   
11531  MzUxMzA1MDU0MTAy                       Universidade Paulista - UNIP   
11532  MzUxNTA2MzUxMDA5                     Faculdade de São VIcente - FSV   

                                             campus_nome campus_external_id  \
0      UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...            1002328   
1      CAMPUS I  SEDE ADMINISTRATIVA PRESIDENTE PRUDE...             657815   
2                    UNIDADE SEDE - Campus Universitario             657884   
3                 CLARETIANO - FACULDADE - Cidade Claret             658817   
4                               RUA AUGUSTA - Consolação            1055967   
...          

Quando criado dessa forma, ele cria uma outra coluna com o índice antigo. Para que isso não ocorra, deve-se passar como parâmetro para tirar essa coluna:
- reset_index(drop=True)

E para que ele mantenha esse novo índice:
- reset_index(inplace=True, drop=True)

In [50]:
df_medicina.reset_index(inplace=True, drop=True)
df_medicina

grau              turno  mensalidade  bolsa_integral_cotas  \
0       Bacharelado           Integral      9715.61                   2.0   
1       Bacharelado           Integral      9650.00                   8.0   
2       Bacharelado           Integral      9564.00                   3.0   
3       Bacharelado           Integral      8600.00                   2.0   
4       Bacharelado           Integral      8200.00                   2.0   
...             ...                ...          ...                   ...   
11528  Licenciatura  Curso a Distância       149.00                   0.0   
11529   Tecnológico  Curso a Distância       149.00                   0.0   
11530   Tecnológico  Curso a Distância       149.00                   0.0   
11531   Tecnológico  Curso a Distância       149.00                   0.0   
11532   Tecnológico  Curso a Distância       144.00                   1.0   

       bolsa_integral_ampla  bolsa_parcial_cotas  bolsa_parcial_ampla  \
0                       5.0                  6.0                 10.0   
1                      15.0                  NaN                  NaN   
2                       5.0                  NaN                  NaN   
3                       9.0                  NaN                  NaN   
4                       3.0                  4.0                  7.0   
...                     ...                  ...                  ...   
11528                   1.0                  NaN                  NaN   
11529                   1.0                  NaN                  NaN   
11530                   1.0                  NaN                  NaN   
11531                   1.0                  NaN                  NaN   
11532                   2.0                  2.0                  5.0   

              curso_id       curso_busca         cidade_busca uf_busca  \
0        1002328574024          Medicina            Sao Paulo       SP   
1          65781564964          Medicina  Presidente Prudente       SP   
2          65788486984          Medicina              Marilia       SP   
3       65881713994834          Medicina            Rio Claro       SP   
4      105596711902804          Medicina            Sao Paulo       SP   
...                ...               ...                  ...      ...   
11528     965912865605        Sociologia      Taboao da Serra       SP   
11529     965913826055  Gestão Comercial      Taboao da Serra       SP   
11530     966013826055  Gestão Comercial                Tatui       SP   
11531     967113826055  Gestão Comercial              Taubate       SP   
11532   65868712869275         Marketing          Sao VIcente       SP   

          cidade_filtro                                  universidade_nome  \
0      MzUxNTA2MTUwMzA4          Universidade Cidade de São Paulo - UNICID   
1      MzUwODAzNjQxNDA2           Universidade do Oeste Paulista - UNOESTE   
2      MzUwOTAzODI5MDA1                   Universidade de Marília - UNIMAR   
3      MzUwNjAyNjQzOTA3  Claretiano - Faculdade - Claretianorc - CLARET...   
4      MzUxNTA2MTUwMzA4                       Faculdade das Américas - FAM   
...                 ...                                                ...   
11528  MzUxNTA2MDUyODA5                       Universidade Paulista - UNIP   
11529  MzUxNTA2MDUyODA5                       Universidade Paulista - UNIP   
11530  MzUxMTA0MzU0MDAz                       Universidade Paulista - UNIP   
11531  MzUxMzA1MDU0MTAy                       Universidade Paulista - UNIP   
11532  MzUxNTA2MzUxMDA5                     Faculdade de São VIcente - FSV   

                                             campus_nome  campus_external_id  \
0      UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...             1002328   
1      CAMPUS I  SEDE ADMINISTRATIVA PRESIDENTE PRUDE...              657815   
2                    UNIDADE SEDE - Campus Universitario              657884   
3                 CLARETIANO - FACULDADE - Cidade Claret           

In [54]:
df_medicina.loc[1:10, 'mensalidade']

1     9650.0
2     9564.0
3     8600.0
4     8200.0
5     8200.0
6     8125.0
7     7990.0
8     7928.0
9     7832.7
10    7755.0
Name: mensalidade, dtype: float64

É possível alterar também o índice do dataframe.

In [55]:
empresa = {'email' : ['jose@email,com', 'joao@email.com'], 'departamento': ['marketing', 'TI'], 'nome' : ['Jose Silva', 'João Guilherme']}

df_empresa = pd.DataFrame(empresa)
df_empresa

email departamento            nome
0  jose@email,com    marketing      Jose Silva
1  joao@email.com           TI  João Guilherme

In [57]:
df_empresa.set_index('email', inplace=True)

In [58]:
df_empresa

departamento            nome
email                                      
jose@email,com    marketing      Jose Silva
joao@email.com           TI  João Guilherme